/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

import database.DBManagement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author phamq
 */
public class Ranking extends javax.swing.JPanel {
    private JLabel[] lb = new JLabel[10];
    /**
     * Creates new form Ranking
     */
    public Ranking() throws SQLException {
        initComponents();
        init();
    }
    
    public void init() throws SQLException {
        DBManagement conn = new DBManagement();
        Statement st = conn.getConn().createStatement();
        String sql = "select * from `player` order by `point` desc";
        ResultSet rs = st.executeQuery(sql);
        int count = 0;
        while(rs.next() && count <5) {
            lb[count * 2] = new JLabel();
            lb[count * 2].setText(rs.getString("name"));

            lb[count * 2].setBorder(BorderFactory.createEtchedBorder());
            pnRank.add(lb[count]);
            
            lb[count * 2 + 1] = new JLabel();
            lb[count * 2 + 1].setText(rs.getString("point"));

            lb[count * 2 + 1].setBorder(BorderFactory.createEtchedBorder());
            pnRank.add(lb[count * 2 + 1]);
        }
        
        conn.closeConnection();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRank = new javax.swing.JLabel();
        pnRank = new javax.swing.JPanel();
        lnName = new javax.swing.JLabel();
        lbPoint = new javax.swing.JLabel();

        lbRank.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbRank.setForeground(new java.awt.Color(0, 102, 102));
        lbRank.setText("Rank");

        pnRank.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnRank.setLayout(new java.awt.GridLayout(6, 2));

        lnName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lnName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnName.setText("Name");
        pnRank.add(lnName);

        lbPoint.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPoint.setText("Point");
        pnRank.add(lbPoint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lbRank)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbPoint;
    private javax.swing.JLabel lbRank;
    private javax.swing.JLabel lnName;
    private javax.swing.JPanel pnRank;
    // End of variables declaration//GEN-END:variables
}
