/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screen;

/**
 *
 * @author phamq
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnWelcome = new javax.swing.JPanel();
        JLBLoading = new javax.swing.JLabel();
        PBLoading = new javax.swing.JProgressBar();
        LBGameName = new javax.swing.JLabel();
        LBWelcome = new javax.swing.JLabel();
        LBBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        PnWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBLoading.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLBLoading.setForeground(new java.awt.Color(255, 255, 255));
        JLBLoading.setText("LOADING: 0%");
        PnWelcome.add(JLBLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        PBLoading.setBackground(new java.awt.Color(255, 255, 255));
        PBLoading.setOpaque(true);
        PnWelcome.add(PBLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 360, 20));

        LBGameName.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LBGameName.setForeground(new java.awt.Color(51, 255, 255));
        LBGameName.setText("REVERSI");
        PnWelcome.add(LBGameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        LBWelcome.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LBWelcome.setForeground(new java.awt.Color(255, 255, 255));
        LBWelcome.setText("WELCOME TO");
        LBWelcome.setToolTipText("");
        PnWelcome.add(LBWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        LBBackground.setForeground(new java.awt.Color(255, 255, 255));
        LBBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/welcome.jpg"))); // NOI18N
        PnWelcome.add(LBBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(640, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLBLoading;
    private javax.swing.JLabel LBBackground;
    private javax.swing.JLabel LBGameName;
    private javax.swing.JLabel LBWelcome;
    public javax.swing.JProgressBar PBLoading;
    private javax.swing.JPanel PnWelcome;
    // End of variables declaration//GEN-END:variables
}
